# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: ""
    name: keycloak
    service:
      type: http
      port: 80

db:
  uri: ""
  name: auditpostgresql
  password: audit
  deployPostgres: false
  port: 5432
  generateDdl: "true"
  ddlAuto: update

auditpostgresql:
   postgresPassword: audit
   resources:
     requests:
       memory: 512Mi
       cpu: 400m
     limits:
      memory: 1024Mi
      cpu: 800m

javaOpts:
  xmx: 1024m
  xms: 768m
  other: -XX:+UnlockExperimentalVMOptions   -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90

image:
  repository: docker.io/activiti/activiti-cloud-audit
  tag: 7.0.111
  pullPolicy: IfNotPresent
service:
  name: audit
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 800m
    memory: 768Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 40
terminationGracePeriodSeconds: 20

## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

ingress:
  ## Set to true to enable ingress record generation
  enabled: false
